import = ["/home/barghest/.config/i3/alacritty/colors.yml", "/home/barghest/.config/i3/alacritty/fonts.yml"]
live_config_reload = true
# theme = "Tokyonight_Night"
# "window.opacity" = 1.0

[colors]
# author = "Folke"
# name = "TokyoNight Night"

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 10

[font.bold]
# family = "FiraCode"

[font.bold_italic]
# family = "FiraCode"

[font.italic]
# family = "FiraCode"

[font.normal]
# family = "FiraCode"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 84
lines = 24

[window.padding]
x = 10
y = 10
