-- Core
require('core.plugins')
require('core.colors')
require('core.configs')
-- Plugins
require('plugins.neotree')
require('plugins.mason')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.conform')
require('plugins.lazygit')
require('plugins.lualine')
require('plugins.surround')
require('plugins.spectre')
require('plugins.toggleterm')
require('plugins.move')
require('plugins.file-operations')
require('plugins.actions-preview')
require('plugins.notify')
require('plugins.bufferline')
require('plugins.ts-tools')
