name: coding-style
on: push

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: yshui/git-clang-format-lint@v1.15
      with:
        base: ${{ github.event.ref }}~1
