name: coding-style
on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - run: git fetch --depth=1 origin ${{ github.event.pull_request.base.sha }}
    - uses: yshui/git-clang-format-lint@v1.15
      with:
        base: ${{ github.event.pull_request.base.sha }}
