vim.api.nvim_command('set number')
vim.api.nvim_command('set encoding=utf-8')
vim.api.nvim_command('set title')
vim.api.nvim_command('set noswapfile')
vim.api.nvim_command('set relativenumber')
vim.api.nvim_command('set autoindent')
vim.api.nvim_command('set background=dark')
vim.api.nvim_command('set completeopt=menuone,noinsert,noselect')
vim.api.nvim_command('set nobackup')
vim.api.nvim_command('set hlsearch')
vim.api.nvim_command('set showcmd')
vim.api.nvim_command('set cmdheight=1')
vim.api.nvim_command('set laststatus=2')
vim.api.nvim_command('set scrolloff=10')
vim.api.nvim_command('set expandtab')
vim.api.nvim_command('set encoding=UTF-8')
vim.api.nvim_command('set langmap=ФИСВУАПРШОЛДЬТЩЗЙКЫЕГМЦЧНЯ;ABCDEFGHIJKLMNOPQRSTUVWXYZ,фисвуапршолдьтщзйкыегмцчня;abcdefghijklmnopqrstuvwxyz')
vim.api.nvim_command('set nosc noru nosm')
vim.api.nvim_command('set lazyredraw')
vim.api.nvim_command('set ignorecase')
vim.api.nvim_command('set smarttab')
vim.api.nvim_command('set shiftwidth=2')
vim.api.nvim_command('set tabstop=2')
vim.api.nvim_command('set nowrap ')
vim.api.nvim_command('set path+=**')
vim.api.nvim_command('set wildignore+=*/node_modules/*')
vim.api.nvim_command('set formatoptions+=r')
vim.api.nvim_command('set filetype=typescript.tsx')

vim.api.nvim_command('filetype plugin indent on')
vim.api.nvim_command('autocmd InsertLeave * set nopaste')

vim.api.nvim_command('syntax enable')


